name: goevent2
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  shared_preferences:
  get:
  accordion: ^2.2.3
  pinput: ^3.0.1
  webview_flutter: ^4.4.3
  http:
  ticket_widget: ^1.0.2
  flutter_phone_direct_caller: ^2.1.1
  like_button: ^2.0.4
  permission_handler:
  url_launcher:
  fluttertoast: ^8.0.9
  intl: 
  dio: ^5.4.0
  get_storage: ^2.0.3
  geolocator:
  flutter_image_stack: ^0.0.6
  geocoding: ^2.0.5
  flutter_widget_from_html_core: any
  carousel_slider: ^4.1.1
  flutter_html: ^3.0.0-alpha.5
  dotted_border:
  razorpay_flutter: ^1.3.4
  image_picker: ^1.0.8 
  screenshot: ^2.1.0
  share_plus: ^7.2.1
  flutter_share: ^2.0.0
  flutter_rating_bar:
  onesignal_flutter: ^5.0.4
  qr_flutter: ^4.0.0
  galleryimage: ^2.0.1
  cached_network_image: ^3.2.3
  flutter_local_notifications: ^9.7.0
  firebase_messaging: ^14.7.7
  cloud_firestore: ^4.13.6
  otp_text_field: ^1.1.3
  flutter_osm_plugin: ^0.70.4
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  open_street_map_search_and_pick: ^0.1.1
  path_provider: any
  firebase_core: any
  package_info_plus: any
  html: any
  image: ^4.2.0

dev_dependencies:
  #flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

#flutter_icons:
 # android: true
  #ios: true
  #image_path: "image/Evson.png"

flutter:
  uses-material-design: true

  assets:
    - image/
    - image/Evson.png

fonts:
  - family: Gilroy Black
    fonts:
      - asset: fonts/Gilroy-Black.ttf
  - family: Gilroy Light
    fonts:
      - asset: fonts/Gilroy-Light.ttf
  - family: Gilroy Heavy
    fonts:
      - asset: fonts/Gilroy-Heavy.ttf
  - family: Gilroy Medium
    fonts:
      - asset: fonts/Gilroy-Medium.ttf
  - family: Gilroy Bold
    fonts:
      - asset: fonts/Gilroy-Bold.otf
  - family: Gilroy ExtraBold
    fonts:
      - asset: fonts/Gilroy-ExtraBold.otf
